"""empty message

Revision ID: 1787264981cf
Revises: 7bc565eef37e
Create Date: 2021-02-09 15:30:27.948433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1787264981cf'
down_revision = '7bc565eef37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('todos', 'completeded')

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completeded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
