"""empty message

Revision ID: 7bc565eef37e
Revises: a9bae9b7fe2a
Create Date: 2021-02-09 15:27:55.428089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc565eef37e'
down_revision = 'a9bae9b7fe2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completeded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completeded')
    # ### end Alembic commands ###
